name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'src/provider/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/provider

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Alibaba Cloud Container Registry
        uses: docker/login-action@v3
        with:
          registry: crpi-uorshhk4a32pmmio.cn-hangzhou.personal.cr.aliyuncs.com
          username: ${{ secrets.ALIYUN_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: src/provider
          push: true
          tags: |
            crpi-uorshhk4a32pmmio.cn-hangzhou.personal.cr.aliyuncs.com/quanttide/qtcloud-write-provider:latest
            crpi-uorshhk4a32pmmio.cn-hangzhou.personal.cr.aliyuncs.com/quanttide/qtcloud-write-provider:${{ github.sha }}
